## Find more values to add here: https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md
version: 3

project:
  id: BPM-SchemaService
  name: BPM-SchemaService

revision:
  commit: "#{CommitHash}#"
  branch: "#{BranchName}#"
