version: 0.0

os: linux
files:
  - source: target
    destination: /tmp/schema-services
  - source: aws/scripts/deploy/deploy.sh
    destination: /tmp/schema-services
  - source: aws/scripts/deploy/undeploy.sh
    destination: /tmp/schema-services
file_exists_behavior: OVERWRITE
    

hooks:
  BeforeInstall: 
    - location: aws/scripts/deploy/undeploy.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: aws/scripts/deploy/deploy.sh
      timeout: 300
      runas: root