version: 0.0
os: windows
files:
  - source: target
    destination: c:\tmp\schema-services  
  - source: aws/scripts/deploy/deploy.cmd
    destination: c:\tmp\schema-services
  - source: aws/scripts/deploy/undeploy.cmd
    destination: c:\tmp\schema-services 
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall: 
    - location: aws/scripts/deploy/undeploy.cmd
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/deploy/deploy.cmd
      timeout: 300
      runas: root
