name: Security Scans
on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main
  workflow_dispatch:
jobs:
  run-scans:
    uses: intelligentautomation/Reusable-Workflows/.github/workflows/security-scans.yml@main
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDS }}
