name: SonarQube Scan
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop", "release/*" ]
  workflow_dispatch:
jobs:   
  sonarqube-scans:
    uses: intelligentautomation/Reusable-Workflows/.github/workflows/sonarqube-scan-with-build.yml@main
    with:
      maven-settings-path: 'aws/m2/settings.xml'
      sonarqube-project-key: 'BPM-SchemaService'
      sonar-host-url: 'https://sonar.ssnc-corp.cloud/'
      keyvault-name: github-ia-kv
      secrets-to-pull: GitHub-Token,SonarQube-Token,AWS-Access-Key-ID,AWS-Secret-Access-Key
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDS }}
