name: Sonargraph Report
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "release/*", "main", "feature/*" ]
  workflow_dispatch:
jobs:
  sonargraph-report:
    uses: intelligentautomation/Reusable-Workflows/.github/workflows/sonargraph-with-build.yml@main
    with:
      keyvault-name: github-ia-kv
      secrets-to-pull: AWS-Access-Key-ID,AWS-Secret-Access-Key,GitHub-Token,CodeCommit-Username,CodeCommit-Password,SonarGraph-Activation-Key,SonarGraph-Host-Url,SonarGraph-Client-Key
      java-version: '21'
      java-distribution: 'corretto'
      maven-version: '3.9.9'
      maven-settings-path: 'aws/m2/settings.xml'
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDS }}
